from typing import TypedDict, Annotated, List
import operator
from langgraph.graph import StateGraph, START, END

# Import nodes
from agents import searcher_node, summarizer_node, fact_checker_node, writer_node

# Maximum retry loops before circuit breaker kicks in
MAX_RETRIES = 5

# Define Graph State
class AgentState(TypedDict):
    messages: Annotated[List[str], operator.add]
    query_type: str
    search_queries: List[str]
    raw_context: str
    current_draft: str
    final_report: str
    errors: Annotated[List[str], operator.add]
    retry_count: int
    source_urls: Annotated[List[str], operator.add]
    workflow_log: Annotated[List[str], operator.add]

def route_fact_check(state: AgentState) -> str:
    errors = state.get("errors", [])
    retry_count = state.get("retry_count", 0)

    if errors and "REJECT" in errors[-1]:
        if retry_count >= MAX_RETRIES:
            print(f">>> ROUTING: Circuit breaker triggered after {retry_count} retries. Sending to Writer with failure report.")
            return "Writer"
        print(f">>> ROUTING: Hallucination flagged (attempt {retry_count}/{MAX_RETRIES})! Routing back to Searcher to retry.")
        return "Searcher"
    else:
        print(">>> ROUTING: Verification passed! Routing to Writer.")
        return "Writer"

def build_graph():
    # Initialize StateGraph
    workflow = StateGraph(AgentState)
    
    # Add nodes
    workflow.add_node("Searcher", searcher_node)
    workflow.add_node("Summarizer", summarizer_node)
    workflow.add_node("FactChecker", fact_checker_node)
    workflow.add_node("Writer", writer_node)
    
    # Define edges
    workflow.add_edge(START, "Searcher")
    workflow.add_edge("Searcher", "Summarizer")
    workflow.add_edge("Summarizer", "FactChecker")
    
    # Conditonal Edge with circuit breaker
    workflow.add_conditional_edges("FactChecker", route_fact_check, {"Searcher": "Searcher", "Writer": "Writer"})
    
    workflow.add_edge("Writer", END)
    
    # Compile Graph
    return workflow.compile()

if __name__ == "__main__":
    import os
    from datetime import datetime

    print("Starting Multi-Agent Research Assistant...\n")
    graph = build_graph()
    
    query = "What are the latest advancements in solid-state batteries?"
    
    # Define initial state
    initial_state = {
        "messages": [f"User query: {query}"],
        "query_type": "",
        "search_queries": [],
        "raw_context": "",
        "current_draft": "",
        "final_report": "",
        "errors": [],
        "retry_count": 0,
        "source_urls": [],
        "workflow_log": []
    }
    
    # Run graph
    print("Invoking graph...\n")
    run_start = datetime.now()
    final_state = None
    for event in graph.stream(initial_state):
        for key, state_snapshot in event.items():
            print(f"--- Node Executed: {key} ---")
            final_state = state_snapshot
    total_elapsed = (datetime.now() - run_start).total_seconds()
            
    # Save the full workflow report
    os.makedirs("output", exist_ok=True)
    report_path = os.path.join("output", "report.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("# Workflow Report -- Multi-Agent Research Assistant\n\n")
        f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        f.write(f"**Research Query:** `{query}`\n\n")
        f.write(f"**Total Execution Time:** {total_elapsed:.1f}s\n\n")
        f.write("## Graph Topology\n\n")
        f.write("```\n")
        f.write("START --> Searcher --> Summarizer --> FactChecker --+--> Writer --> END\n")
        f.write("                                                   |\n")
        f.write("                                                   +--> Searcher (retry on REJECT)\n")
        f.write("```\n\n")
        f.write("## Detailed Agent Execution Log\n")
        if final_state:
            for entry in final_state.get("workflow_log", []):
                f.write(entry)
            f.write("\n\n---\n\n")
            f.write("*Report generated by Multi-Agent Research Assistant*\n")
        
    print(f"\n--- Process Complete! Workflow report saved to {report_path} ---")
